Module5_PL/lab/BananaStore/product/urls.py
from django.conf.urls import url
from . import views

app_name = "product_ns"

urlpatterns = [
    url(r'^$', views.product, name="index"),
    url(r'^(?P<product>\D+)/', views.product, name="details"),
]

Module5_PL/lab/BananaStore/urls.py
from django.urls import include
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',TemplateView.as_view(template_name='homepage.html')),
    url(r'^product/', include('BananaStore.product.urls',namespace="product_ns")),
]

Module5_PL/lab/BananaStore/product/views.py
from django.shortcuts import render
from django.template.response import TemplateResponse
from django.conf import settings

# Create your views here.


def product(request, product="BananaChips"):
    discount = settings.DISCOUNT
    
    price = request.GET.get('price', 'N/A')
    calories = request.GET.get('nutrition', 'N/A')
    origin = request.GET.get('origin', 'N/A')
    prices = ((0, price), (1, float(price)*float((100-discount)/100)))
    nutritionFacts = [calories, 10, 20, 30]
    # Create an information dictionary
    info = {'product': product, 'prices': prices,
            'nutritionFacts': nutritionFacts, 'origin': origin}
    return TemplateResponse(request, 'product/details.html', {'info': info})

Module5_PL/lab/BananaStore/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Freelancer - Start Bootstrap Theme</title>

    <!-- Custom fonts for this theme -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet"
        type="text/css">

    <!-- Theme CSS -->
    <link href="{% static 'css/freelancer.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="/">Banana Store</a>
            <button
                class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded"
                type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive"
                aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                </ul>
            </div>
        </div>
    </nav>

    <!-- Masthead -->
    <header class="masthead bg-primary text-white text-center">
        <div class="container d-flex align-items-center flex-column">

            <!-- Masthead Heading -->
            <h1 class="masthead-heading text-uppercase mb-0">Banana Store</h1>

            <!-- Icon Divider -->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon">
                    <i class="fas fa-star"></i>
                </div>
                <div class="divider-custom-line"></div>
            </div>

            <!-- Masthead Subheading -->
            <p class="masthead-subheading font-weight-light mb-0">CS 555 - Django Web Development</p>

        </div>
    </header>

    <!-- Main Section -->
    <section class="page-section portfolio" id="portfolio">
            <!-- Main Block -->
            {% block main %}{% endblock %}
    </section>

    <!-- Copyright Section -->
    <section class="copyright py-4 text-center text-white">
        <div class="container">
            <small>Copyright &copy; CityU 2019</small>
        </div>
    </section>

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-to-top d-lg-none position-fixed ">
        <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Contact Form JavaScript -->
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/contact_me.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/freelancer.min.js' %}"></script>

</body>

</html>

Module5_PL/lab/BananaStore/templates/divider.html
<div class="divider-custom">
    <div class="divider-custom-line"></div>
    <div class="divider-custom-icon">
        <i class="fas fa-star"></i>
    </div>
    <div class="divider-custom-line"></div>
</div>

Module5_PL/lab/BananaStore/templates/homepage.html
{% extends "base.html" %} 
{% load static %}
{% block main%}

<!-- Main Section Heading -->
<h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Homepage</h2>

<!-- Icon Divider -->
<div class="divider-custom">
    <div class="divider-custom-line"></div>
    <div class="divider-custom-icon">
        <i class="fas fa-star"></i>
    </div>
    <div class="divider-custom-line"></div>
</div>

<!-- Main Content -->
<table style="margin-left:auto; margin-right:auto;border-collapse: separate;border-spacing: 50px 0;">
    <tr>
        <td><img src="http://bit.ly/2IPoVn9" alt="Banana Bread" height="200" width="200"></td>
        <td><img src="http://bit.ly/2Bf6Z0V" alt="Banana Chips" height="200" width="200"></td>
        <td><img src="http://bit.ly/2IIBbG7" alt="Banana Juice" height="200" width="200"></td>
        <td><img src="http://bit.ly/3292pgJ" alt="Banana Muffins" height="200" width="200"></td>
        <td><img src="http://bit.ly/31dqDFt" alt="Banana Pancake" height="200" width="200"></td>
    </tr>
    <tr style="text-align: center;margin: 50px;font-size: 30px;font-weight: bold;">
        <td><a class="btn btn-primary" href="{% url 'product_ns:details' 'Banana Bread' %}?price=10&nutrition=100cal&origin=Seattle" role="button">Banana Bread</a></td>
        <td><a class="btn btn-primary" href="{% url 'product_ns:details' 'Banana Chips' %}?price=30&nutrition=200cal&origin=UnknownMonkeyIsland" role="button">Banana Chips</a></td>
        <td><a class="btn btn-primary" href="{% url 'product_ns:details' 'Banana Juice' %}?price=20&nutrition=100cal&origin=Cali" role="button">Banana Juice</a></td>
        <td><a class="btn btn-primary" href="{% url 'product_ns:details' 'Banana Muffins' %}?price=15&nutrition=400cal&origin=Texas" role="button">Banana Muffins</a></td>
        <td><a class="btn btn-primary" href="{% url 'product_ns:details' 'Banana Pancake' %}?price=50&nutrition=1000cal&origin=Florida" role="button">Banana Pancake</a></td>
    </tr>
</table>

{% include "divider.html" %}
<div style="text-align: center;">
    <button type="button" class="btn btn-danger">
        DISCOUNT <span class="badge badge-light">{{DISCOUNT}}%</span>
    </button>
    <br/><br/><br/>
    <img src="{% static 'img/organic_icon.png' %}" class="navbar-brand js-scroll-trigger" alt="site_icon">
</div>

{% endblock%}

Module5_PL/lab/BananaStore/templates/product/details.html
{% extends "base.html" %} {% block main%}

<!-- Main Section Heading -->
<h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Product Information</h2>

<!-- Icon Divider -->
<div class="divider-custom">
    <div class="divider-custom-line"></div>
    <div class="divider-custom-icon">
        <i class="fas fa-star"></i>
    </div>
    <div class="divider-custom-line"></div>
</div>

<!-- Main Content -->
<div style="text-align: center;">
    <p>Product: {{ info.product }}</p>
    <p>Price: List Price ${{ info.prices.0.1 }}, Discounted Price ${{ info.prices.1.1 }}</p>
    <p>Nutrition Facts: Calories {{ info.nutritionFacts.0 }}, Total fat {{ info.nutritionFacts.1 }}, Total carbohydrate {{ info.nutritionFacts.2 }}, Protein {{ info.nutritionFacts.3 }}</p>
    <p>Origin: {{ info.origin }}</p>
</div>
{% endblock%}